// lib/tools-meta.js — Tool metadata and registry (27+ tools)
const TOOL_META = {
  navigate: { category: 'browser', readonly: false, level: 'interact' },
  read_page: { category: 'browser', readonly: true, level: 'read' },
  screenshot: { category: 'browser', readonly: true, level: 'read' },
  get_page_elements: { category: 'browser', readonly: true, level: 'inspect' },
  get_page_snapshot: { category: 'browser', readonly: true, level: 'inspect' },
  google_search: { category: 'search', readonly: true, level: 'read' },
  web_search: { category: 'search', readonly: true, level: 'read' },
  scrape_url: { category: 'search', readonly: true, level: 'read' },
  inspect_dom_js: { category: 'interact', readonly: true, level: 'inspect' },
  mutate_dom_js: { category: 'interact', readonly: false, level: 'write_form', confirm: true },
  click_element: { category: 'interact', readonly: false, level: 'interact' },
  fill_form: { category: 'interact', readonly: false, level: 'write_form' },
  scroll_page: { category: 'browser', readonly: true, level: 'read' },
  hover_element: { category: 'interact', readonly: true, level: 'inspect' },
  wait_for: { category: 'interact', readonly: true, level: 'inspect' },
  detect_block: { category: 'browser', readonly: true, level: 'read' },
  verify_action: { category: 'browser', readonly: true, level: 'read' },
  wait_network_idle: { category: 'browser', readonly: true, level: 'read' },
  send_email: { category: 'comms', readonly: false, level: 'send', confirm: true },
  prepare_email_draft: { category: 'comms', readonly: false, level: 'prepare' },
  check_emails: { category: 'comms', readonly: true, level: 'read' },
  linkedin_search: { category: 'comms', readonly: true, level: 'read' },
  linkedin_send_message: { category: 'comms', readonly: false, level: 'send', confirm: true },
  whatsapp_send: { category: 'comms', readonly: false, level: 'send', confirm: true },
  save_to_kb: { category: 'knowledge', readonly: false, level: 'write_kb', confirm: true },
  search_kb: { category: 'knowledge', readonly: true, level: 'read' },
  kb_delete: { category: 'knowledge', readonly: false, level: 'destructive', confirm: true },
  create_file: { category: 'files', readonly: false, level: 'write_local' },
  save_local_file: { category: 'files', readonly: false, level: 'write_local' },
  read_local_file: { category: 'files', readonly: true, level: 'read' },
  create_task: { category: 'tasks', readonly: false, level: 'write_local' },
  list_tasks: { category: 'tasks', readonly: true, level: 'read' },
  delete_task: { category: 'tasks', readonly: false, level: 'destructive', confirm: true },
  save_memory: { category: 'memory', readonly: false, level: 'write_local' },
  recall_memory: { category: 'memory', readonly: true, level: 'read' },
};

const COBRA_TOOLS = [
  { type: 'function', function: { name: 'navigate', description: 'Navigate browser to a URL', parameters: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } } },
  { type: 'function', function: { name: 'read_page', description: 'Read current page content', parameters: { type: 'object', properties: {}, required: [] } } },
  { type: 'function', function: { name: 'screenshot', description: 'Take screenshot of current page', parameters: { type: 'object', properties: {}, required: [] } } },
  { type: 'function', function: { name: 'get_page_elements', description: 'Get interactive elements on page', parameters: { type: 'object', properties: { filter: { type: 'string' } }, required: [] } } },
  { type: 'function', function: { name: 'click_element', description: 'Click an element on the page', parameters: { type: 'object', properties: { selector: { type: 'string' } }, required: ['selector'] } } },
  { type: 'function', function: { name: 'fill_form', description: 'Fill form fields', parameters: { type: 'object', properties: { fields: { type: 'string' } }, required: ['fields'] } } },
  { type: 'function', function: { name: 'google_search', description: 'Search Google', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'scrape_url', description: 'Scrape URL content', parameters: { type: 'object', properties: { url: { type: 'string' } }, required: ['url'] } } },
  { type: 'function', function: { name: 'inspect_dom_js', description: 'Execute read-only JavaScript', parameters: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } } },
  { type: 'function', function: { name: 'mutate_dom_js', description: 'Execute mutative JavaScript (requires confirmation)', parameters: { type: 'object', properties: { code: { type: 'string' } }, required: ['code'] } } },
  { type: 'function', function: { name: 'send_email', description: 'Send email (requires confirmation)', parameters: { type: 'object', properties: { to: { type: 'string' }, subject: { type: 'string' }, body: { type: 'string' } }, required: ['to', 'subject', 'body'] } } },
  { type: 'function', function: { name: 'save_to_kb', description: 'Save to knowledge base', parameters: { type: 'object', properties: { domain: { type: 'string' }, type: { type: 'string' }, name: { type: 'string' }, content: { type: 'string' } }, required: ['domain', 'type', 'name', 'content'] } } },
  { type: 'function', function: { name: 'search_kb', description: 'Search knowledge base', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'create_task', description: 'Create a multi-step task', parameters: { type: 'object', properties: { name: { type: 'string' }, steps: { type: 'string' } }, required: ['name', 'steps'] } } },
  { type: 'function', function: { name: 'list_tasks', description: 'List all tasks', parameters: { type: 'object', properties: {}, required: [] } } },
];

module.exports = { TOOL_META, COBRA_TOOLS };
