// modules/risk/taxonomy.js — Tool risk registry
// Source: server.js lines 91-185

const TOOL_RISK_TAXONOMY = {
  navigate:        { level:'interact', confirm:false, batchable:true, truth:'Naviga a URL.' },
  read_page:       { level:'read', confirm:false, batchable:true, truth:'Legge contenuto testuale pagina.' },
  screenshot:      { level:'read', confirm:false, batchable:true, truth:'Screenshot pagina corrente.' },
  get_page_elements:{ level:'inspect', confirm:false, batchable:true, truth:'Lista elementi interattivi.' },
  get_page_snapshot:{ level:'inspect', confirm:false, batchable:true, truth:'Snapshot strutturato.' },
  google_search:   { level:'read', confirm:false, batchable:true, truth:'Ricerca Google.' },
  web_search:      { level:'read', confirm:false, batchable:true, truth:'Ricerca web.' },
  check_emails:    { level:'read', confirm:false, batchable:true, truth:'Controlla email IMAP.' },
  scrape_url:      { level:'read', confirm:false, batchable:true, truth:'Scrape URL background.' },
  crawl_website:   { level:'read', confirm:false, batchable:true, truth:'Crawl multi-pagina.' },
  extract_data:    { level:'read', confirm:false, batchable:true, truth:'Estrae dati strutturati.' },
  search_kb:       { level:'read', confirm:false, batchable:true, truth:'Cerca in KB.' },
  list_tasks:      { level:'read', confirm:false, batchable:true, truth:'Lista job.' },
  list_local_files:{ level:'read', confirm:false, batchable:true, truth:'Lista file locali.' },
  read_local_file: { level:'read', confirm:false, batchable:true, truth:'Legge file locale.' },
  search_local_files:{ level:'read', confirm:false, batchable:true, truth:'Cerca file locali.' },
  batch_scrape:    { level:'read', confirm:false, batchable:true, truth:'Scrape parallelo.' },
  scroll_page:     { level:'read', confirm:false, batchable:true, truth:'Scroll pagina.' },
  hover_element:   { level:'inspect', confirm:false, batchable:true, truth:'Hover su elemento.' },
  wait_for:        { level:'inspect', confirm:false, batchable:true, truth:'Attende elemento/tempo.' },
  switch_tab:      { level:'inspect', confirm:false, batchable:true, truth:'Cambia tab browser.' },
  request_human_takeover:{ level:'interact', confirm:false, batchable:false, truth:'Cede controllo.' },
  inspect_dom_js:  { level:'inspect', confirm:false, batchable:true, truth:'JS lettura. No fetch/submit.' },
  prepare_email_draft:      { level:'prepare', confirm:false, batchable:true, truth:'Bozza email in memoria.' },
  prepare_whatsapp_message: { level:'prepare', confirm:false, batchable:true, truth:'Prepara testo WhatsApp.' },
  prepare_linkedin_message: { level:'prepare', confirm:false, batchable:true, truth:'Prepara testo LinkedIn.' },
  create_file:     { level:'write_local', confirm:false, batchable:true, truth:'Crea file sandbox.' },
  save_local_file: { level:'write_local', confirm:false, batchable:true, truth:'Salva file locale.' },
  save_memory:     { level:'write_local', confirm:false, batchable:true, truth:'Salva memoria persistente.' },
  fill_form:       { level:'write_form', confirm:false, batchable:true, truth:'Compila form senza submit.' },
  select_option:   { level:'write_form', confirm:false, batchable:true, truth:'Seleziona opzione dropdown.' },
  click_element:   { level:'interact', confirm:false, batchable:true, truth:'Click elemento.' },
  press_key:       { level:'interact', confirm:false, batchable:true, truth:'Preme tasto.' },
  drag_drop:       { level:'interact', confirm:false, batchable:true, truth:'Drag & drop.' },
  upload_file:     { level:'interact', confirm:false, batchable:true, truth:'Upload file.' },
  type_human:      { level:'interact', confirm:false, batchable:true, truth:'Digitazione realistica.' },
  key_combo:       { level:'interact', confirm:false, batchable:true, truth:'Combo tastiera.' },
  select_dropdown: { level:'interact', confirm:false, batchable:true, truth:'Seleziona dropdown custom.' },
  set_datepicker:  { level:'interact', confirm:false, batchable:true, truth:'Imposta datepicker.' },
  clipboard_write: { level:'interact', confirm:false, batchable:true, truth:'Scrive clipboard.' },
  detect_block:    { level:'read', confirm:false, batchable:true, truth:'Rileva CAPTCHA/2FA.' },
  verify_action:   { level:'read', confirm:false, batchable:true, truth:'Verifica risultato.' },
  read_table:      { level:'read', confirm:false, batchable:true, truth:'Legge tabella.' },
  wait_network_idle:{ level:'read', confirm:false, batchable:true, truth:'Attende network idle.' },
  mutate_dom_js:   { level:'write_form', confirm:true, batchable:false, ttl:60, truth:'JS mutativo DOM.' },
  execute_js:      { level:'write_form', confirm:false, batchable:false, truth:'Legacy JS execution.' },
  save_to_kb:      { level:'write_kb', confirm:true, batchable:true, truth:'Salva entry KB.' },
  kb_update:       { level:'write_kb', confirm:true, batchable:false, truth:'Modifica entry KB.' },
  send_email:      { level:'send', confirm:true, batchable:true, ttl:600, truth:'Invia email SMTP.' },
  open_whatsapp:   { level:'send_prepare', confirm:false, batchable:false, ttl:300, truth:'Apre WhatsApp precompilato.' },
  open_linkedin:   { level:'send_prepare', confirm:false, batchable:false, ttl:300, truth:'Apre LinkedIn.' },
  linkedin_search:       { level:'read', confirm:false, batchable:true, truth:'Cerca profili LinkedIn.' },
  linkedin_profile:      { level:'read', confirm:false, batchable:true, truth:'Estrae profilo LinkedIn.' },
  linkedin_inbox:        { level:'read', confirm:false, batchable:true, truth:'Legge inbox LinkedIn.' },
  linkedin_read_thread:  { level:'read', confirm:false, batchable:true, truth:'Legge thread LinkedIn.' },
  linkedin_send_message: { level:'send', confirm:true, batchable:false, ttl:300, truth:'Invia messaggio LinkedIn.' },
  linkedin_connect:      { level:'send', confirm:true, batchable:false, ttl:300, truth:'Collegamento LinkedIn.' },
  whatsapp_send:         { level:'send', confirm:true, batchable:false, ttl:300, truth:'Invia WhatsApp.' },
  whatsapp_unread:       { level:'read', confirm:false, batchable:true, truth:'Legge WhatsApp non letti.' },
  whatsapp_read_thread:  { level:'read', confirm:false, batchable:true, truth:'Legge thread WhatsApp.' },
  kb_delete:       { level:'destructive', confirm:true, batchable:false, ttl:60, truth:'Cancella entry KB.' },
  delete_task:     { level:'destructive', confirm:true, batchable:false, ttl:60, truth:'Cancella job.' },
  create_task:     { level:'write_local', confirm:false, batchable:true, truth:'Crea job.' },
  run_task:        { level:'interact', confirm:false, batchable:false, truth:'Esegue job salvato.' },
  // Alias handlers (registrati come alias in handler index)
  read_inbox:      { level:'read', confirm:false, batchable:true, truth:'Alias di check_emails.' },
  send_whatsapp:   { level:'send', confirm:true, batchable:false, ttl:300, truth:'Alias di whatsapp_send.' },
  send_linkedin:   { level:'send', confirm:true, batchable:false, ttl:300, truth:'Alias di linkedin_send_message.' },
  web_search:      { level:'read', confirm:false, batchable:true, truth:'Alias di google_search.' },
  execute_js:      { level:'write_form', confirm:false, batchable:false, truth:'Legacy JS execution alias.' },
};

function getToolRiskSpec(toolName) {
  return TOOL_RISK_TAXONOMY[toolName] || {
    level: 'destructive', confirm: true, batchable: false, ttl: 60,
    truth: `Tool sconosciuto "${toolName}". Default: destructive.`,
  };
}

module.exports = { TOOL_RISK_TAXONOMY, getToolRiskSpec };
